export interface QuoteWordsEntry {
    text: string;
    source: string;
    translation?: string;
  }
export const QWordsList: QuoteWordsEntry[] = [
    { text: "I can do all things through Christ who strengthens me", source: "Philippians 4:13", translation: "NKJV" },
    { text: "Your word is a lamp unto my feet and a light unto my path", source: "Psalm 119:105", translation: "KJV"},
    { text: "Trust in the Lord with all your heart, and lean not on your own understanding", source: "Proverbs 3:5", translation: "NKJV"},
    { text: "All Scripture is given by inspiration of God and is profitable for doctrine, for reproof, for correction, for instruction in righteousness", source: "2 Timothy 3:16", translation: "NKJV"},
    { text: "But seek ye first the kingdom of God and His righteousness and all these things shall be added unto you", source: "Matthew 6:33", translation: "KJV"},
    { text: "Now to Him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us", source: "Ephesians 3:20", translation: "NKJV"},
    { text: "For the Son of man is come to seek and to save that which was lost", source: "Luke 19:10", translation: "KJV"},
    { text: "If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness", source: "1 John 1:9", translation: "KJV"},
    { text: "For this is the love of God, that we keep His commandments, and His commandments are not grievous", source: "1 John 5:3", translation: "KJV"},
    { text: "Blessed are they that mourn, for they shall be comforted", source: "Matthew 5:4", translation: "KJV"},
    { text: "The Lord is my shepherd; I shall not want", source: "Psalm 23:1", translation: "KJV"},
    { text: "Pray without ceasing", source: "1 Thessalonians 5:17", translation: "KJV"},
    { text: "Jesus Christ is the same yesterday, today, and forever", source: "Hebrews 13:8", translation: "NKJV"},
    { text: "With God all things are possible", source: "Matthew 19:26", translation: "KJV"},
    { text: "Be still, and know that I am God", source: "Psalm 46:10", translation: "KJV"},
    { text: "Cast all your care upon Him, for He cares for you", source: "1 Peter 5:7", translation: "NKJV"},
    { text: "For we walk by faith, not by sight", source: "2 Corinthians 5:7", translation: "KJV"},
    { text: "Delight yourself also in the Lord, and He shall give you the desires of your heart", source: "Psalm 37:4", translation: "NKJV"},
    { text: "The fear of the Lord is the beginning of wisdom", source: "Proverbs 9:10", translation: "KJV"},
    { text: "For God is not the author of confusion but of peace", source: "1 Corinthians 14:33", translation: "NKJV"},
    { text: "Let everything that has breath praise the Lord", source: "Psalm 150:6", translation: "NKJV"},
    { text: "Rejoice in the Lord always. Again I will say, rejoice!", source: "Philippians 4:4", translation: "NKJV"},
    { text: "Draw near to God and He will draw near to you", source: "James 4:8", translation: "NKJV"},
    { text: "Therefore submit to God. Resist the devil and he will flee from you", source: "James 4:7", translation: "NKJV"},
    { text: "A soft answer turneth away wrath", source: "Proverbs 15:1", translation: "KJV"},
    { text: "This is the day which the Lord hath made; we will rejoice and be glad in it", source: "Psalm 118:24", translation: "KJV"},
    { text: "He must increase, but I must decrease", source: "John 3:30", translation: "KJV"},
    { text: "Blessed are the pure in heart, for they shall see God", source: "Matthew 5:8", translation: "NKJV"},
    { text: "Commit your way to the Lord, trust also in Him, and He shall bring it to pass", source: "Psalm 37:5", translation: "NKJV"},
    { text: "For the wages of sin is death, but the gift of God is eternal life through Jesus Christ our Lord", source: "Romans 6:23", translation: "KJV"},
    { text: "Thy word have I hid in mine heart, that I might not sin against thee", source: "Psalm 119:11", translation: "KJV"},
    { text: "Blessed are the merciful, for they shall obtain mercy", source: "Matthew 5:7", translation: "NKJV"},
    { text: "God is our refuge and strength, a very present help in trouble", source: "Psalm 46:1", translation: "KJV"},
    { text: "He who dwells in the secret place of the Most High shall abide under the shadow of the Almighty", source: "Psalm 91:1", translation: "NKJV"},
    { text: "The Lord is good, a stronghold in the day of trouble", source: "Nahum 1:7", translation: "NKJV" },
    { text: "We love Him because He first loved us", source: "1 John 4:19", translation: "NKJV" },
    { text: "Let not your heart be troubled, neither let it be afraid", source: "John 14:27", translation: "KJV" },
    { text: "For by grace you have been saved through faith, and that not of yourselves", source: "Ephesians 2:8", translation: "NKJV" },
    { text: "The Lord will fight for you, and you shall hold your peace", source: "Exodus 14:14", translation: "NKJV" },
    { text: "In everything give thanks", source: "1 Thessalonians 5:18", translation: "KJV" },
    { text: "Blessed are the meek, for they shall inherit the earth", source: "Matthew 5:5", translation: "KJV" },
    { text: "Greater love has no one than this, than to lay down one's life for his friends", source: "John 15:13", translation: "NKJV" },
    { text: "The name of the Lord is a strong tower; the righteous run to it and are safe", source: "Proverbs 18:10", translation: "NKJV" },
    { text: "Create in me a clean heart, O God; and renew a right spirit within me", source: "Psalm 51:10", translation: "KJV" },
    { text: "For with God nothing shall be impossible", source: "Luke 1:37", translation: "KJV" },
    { text: "In the beginning God created the heavens and the earth", source: "Genesis 1:1", translation: "NKJV"},
    { text: "Behold, I am with you always, even to the end of the age", source: "Matthew 28:20", translation: "NKJV" },
    { text: "The Lord is my light and my salvation; whom shall I fear?", source: "Psalm 27:1", translation: "NKJV" },
    { text: "Blessed are the peacemakers: for they shall be called the children of God", source: "Matthew 5:9", translation: "KJV" },
    { text: "I will never leave you nor forsake you", source: "Hebrews 13:5", translation: "NKJV" },
    { text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest", source: "Matthew 11:28", translation: "KJV" },
    { text: "Fear not, for I am with you; be not dismayed, for I am your God", source: "Isaiah 41:10", translation: "NKJV" },
    { text: "This is my commandment, That ye love one another, as I have loved you", source: "John 15:12", translation: "KJV" },
    { text: "Do not be overcome by evil, but overcome evil with good", source: "Romans 12:21", translation: "NKJV" },
    { text: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled", source: "Matthew 5:6", translation: "KJV" },
    { text: "I am the way, the truth, and the life", source: "John 14:6", translation: "NKJV" },
    { text: "Let your light so shine before men that they may see your good works and glorify your Father which is in heaven", source: "Matthew 5:16", translation: "KJV" },
    { text: "The Lord is near to all who call upon Him", source: "Psalm 145:18", translation: "NKJV" },
    { text: "Watch and pray, that ye enter not into temptation", source: "Matthew 26:41", translation: "KJV" },
    { text: "My grace is sufficient for you, for My strength is made perfect in weakness", source: "2 Corinthians 12:9", translation: "NKJV" },
    { text: "The Lord shall preserve thy going out and thy coming in from this time forth", source: "Psalm 121:8", translation: "KJV" },
    { text: "He who believes in Me, though he may die, he shall live", source: "John 11:25", translation: "NKJV" },
    { text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!", source: "Psalm 133:1", translation: "KJV" },
    { text: "Be strong and courageous. Do not be afraid or discouraged", source: "Joshua 1:9", translation: "NKJV" },
    { text: "Blessed are the merciful: for they shall obtain mercy", source: "Matthew 5:7", translation: "KJV" },
    { text: "Set your mind on things above, not on things on the earth", source: "Colossians 3:2", translation: "NKJV" },
    { text: "Let love be without hypocrisy. Abhor what is evil; cling to what is good", source: "Romans 12:9", translation: "NKJV" },
    { text: "For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding", source: "Proverbs 2:6", translation: "KJV" },
    { text: "Blessed is the man who trusts in the Lord", source: "Jeremiah 17:7", translation: "NKJV" },
    { text: "And do not be conformed to this world, but be transformed by the renewing of your mind", source: "Romans 12:2", translation: "NKJV"},
    { text: "Call unto Me and I will answer thee, and shew thee great and mighty things which thou knowest not", source: "Jeremiah 33:3", translation: "KJV"},
    { text: "Now faith is the substance of things hoped for, the evidence of things not seen", source: "Hebrews 11:1", translation: "KJV"},
    { text: "Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear", source: "Hebrews 11:3", translation: "KJV"},
    { text: "Here is the patience of the saints: here are they that keep the commandments of God and the faith of Jesus", source: "Revelation 14:12", translation: "KJV"},
    { text: "Then I saw another angel flying in the midst of heaven, having the everlasting gospel to preach to those who dwell on the earth", source: "Revelation 14:6", translation: "NKJV"},
    { text: "Fear God and give glory to Him, for the hour of His judgment has come; and worship Him who made heaven and earth, the sea and springs of water", source: "Revelation 14:7", translation: "NKJV"},
    { text: "Thou shalt have no other gods before me", source: "Exodus 20:3", translation: "KJV"},
    { text: "Thou shalt not make unto thee any graven image... thou shalt not bow down thyself to them nor serve them", source: "Exodus 20:4-5", translation: "KJV"},
    { text: "Thou shalt not take the name of the Lord thy God in vain; for the Lord will not hold him guiltless that taketh His name in vain", source: "Exodus 20:6", translation: "KJV"},
    { text: "Remember the Sabbath day, to keep it holy. Six days shalt thou labour and do all thy work, but the seventh day is the Sabbath of the Lord thy God", source: "Exodus 20:8-10", translation: "KJV"},
    { text: "Honour thy father and thy mother that they days may be long upon the land which the Lord they God giveth thee", source: "Exodus 20:12", translation: "KJV"},
    { text: "Thou shalt not kill", source: "Exodus 20:13", translation: "KJV"},
    { text: "Thou shalt not commit adultery", source: "Exodus 20:14", translation: "KJV"},
    { text: "Thou shalt not steal", source: "Exodus 20:15", translation: "KJV"},
    { text: "Thou shalt not bear witness against they neighbour", source: "Exodus 20:16", translation: "KJV"},
    { text: "Thou shalt not covet... any thing that is thy neighbour's", source: "Exodus 20:17", translation: "KJV"},
    { text: "You shall love the Lord your God with all your heart, with all your soul, with all your strength, and with all your mind", source: "Luke 10:27", translation: "NKJV"},
    { text: "You shall love your neighbour as yourself", source: "Matthew 22:39", translation: "NKJV"},
    { text: "For it is God who works in you both to will and to do for His good pleasure", source: "Philippians 2:13", translation: "NKJV"},
    { text: "The Lord is near to those who have a broken heart, and saves such as have a contrite spirit", source: "Psalm 34:18", translation: "NKJV"},
    { text: "The Lord gave, and the Lord hath taken away; blessed be the name of the Lord", source: "Job 1:21", translation: "KJV"},
    { text: "...God is faithful, who will not allow you to be tempted beyond what you are able, but with the temptation will also make the way of escape...", source: "1 Corinthians 10:13", translation: "NKJV"},
    { text: "...And the Lord added to the church daily those who were being saved", source: "Acts 2:46", translation: "NKJV"},
    { text: "If you can believe, all things are possible to him who believes", source: "Mark 9:23", translation: "NKJV"},
    { text: "If you abide in Me, and My words abide in you, you will ask what you desire, and it shall be done for you", source: "John 15:7", translation: "NKJV"},
    { text: "If you keep My commandments, you will abide in My love, just as I have kept My Father's commandments and abide in His love", source: "John 15:10", translation: "NKJV"},
    { text: "These things I have spoken to you, that My joy may remain in you, and that your joy may be full", source: "John 15:11", translation: "NKJV"},
    { text: "In the beginning was the Word, and the Word was with God, and the Word was God.", source: "John 1:1", translation: "NKJV"},
    { text: "And the Word became flesh and dwelt among us, and we beheld His glory, glory as of the only begotten of the Father, full of grace and truth", source: "John 1:14", translation: "NKJV"},
    { text: "And she will bring forth a Son, and you shall call His name Jesus, for He will save His people from their sins", source: "Matthew 1:21", translation: "NKJV"},
    { text: "Behold! The Lamb of God who takes away the sin of the world!", source: "John 1:29", translation: "NKJV"}
];
